export const COUNTRIES = [
  { name: 'Afghanistan', value: 'afg' },
  { name: 'Albania', value: 'alb' },
  { name: 'Algeria', value: 'dza' },
  { name: 'Andorra', value: 'and' },
  { name: 'Angola', value: 'ago' },
  { name: 'Antigua and Barbuda', value: 'atg' },
  { name: 'Argentina', value: 'arg' },
  { name: 'Armenia', value: 'arm' },
  { name: 'Australia', value: 'aus' },
  { name: 'Austria', value: 'aut' },
  { name: 'Azerbaijan', value: 'aze' },
  { name: 'Bahamas', value: 'bhs' },
  { name: 'Bahrain', value: 'bhr' },
  { name: 'Bangladesh', value: 'bgd' },
  { name: 'Barbados', value: 'brb' },
  { name: 'Belarus', value: 'blr' },
  { name: 'Belgium', value: 'bel' },
  { name: 'Belize', value: 'blz' },
  { name: 'Benin', value: 'ben' },
  { name: 'Bhutan', value: 'btn' },
  { name: 'Bolivia', value: 'bol' },
  { name: 'Bosnia and Herzegovina', value: 'bih' },
  { name: 'Botswana', value: 'bwa' },
  { name: 'Brazil', value: 'bra' },
  { name: 'Brunei', value: 'brn' },
  { name: 'Bulgaria', value: 'bgr' },
  { name: 'Burkina Faso', value: 'bfa' },
  { name: 'Burundi', value: 'bdi' },
  { name: 'Cambodia', value: 'khm' },
  { name: 'Cameroon', value: 'cmr' },
  { name: 'Canada', value: 'can' },
  { name: 'Cape Verde', value: 'cpv' },
  { name: 'Central African Republic', value: 'caf' },
  { name: 'Chad', value: 'tcd' },
  { name: 'Chile', value: 'chl' },
  { name: 'China', value: 'chn' },
  { name: 'Colombia', value: 'col' },
  { name: 'Comoros', value: 'com' },
  { name: 'Congo (Brazzaville)', value: 'cog' },
  { name: 'Congo (Kinshasa)', value: 'cod' },
  { name: 'Costa Rica', value: 'cri' },
  { name: 'Croatia', value: 'hrv' },
  { name: 'Cuba', value: 'cub' },
  { name: 'Cyprus', value: 'cyp' },
  { name: 'Czech Republic', value: 'cze' },
  { name: 'Denmark', value: 'dnk' },
  { name: 'Djibouti', value: 'dji' },
  { name: 'Dominica', value: 'dma' },
  { name: 'Dominican Republic', value: 'dom' },
  { name: 'Ecuador', value: 'ecu' },
  { name: 'Egypt', value: 'egy' },
  { name: 'El Salvador', value: 'slv' },
  { name: 'Equatorial Guinea', value: 'gnq' },
  { name: 'Eritrea', value: 'eri' },
  { name: 'Estonia', value: 'est' },
  { name: 'Eswatini', value: 'swz' },
  { name: 'Ethiopia', value: 'eth' },
  { name: 'Fiji', value: 'fji' },
  { name: 'Finland', value: 'fin' },
  { name: 'France', value: 'fra' },
  { name: 'Gabon', value: 'gab' },
  { name: 'Gambia', value: 'gmb' },
  { name: 'Georgia', value: 'geo' },
  { name: 'Germany', value: 'deu' },
  { name: 'Ghana', value: 'gha' },
  { name: 'Greece', value: 'grc' },
  { name: 'Grenada', value: 'grd' },
  { name: 'Guatemala', value: 'gtm' },
  { name: 'Guinea', value: 'gin' },
  { name: 'Guinea-Bissau', value: 'gnb' },
  { name: 'Guyana', value: 'guy' },
  { name: 'Haiti', value: 'hti' },
  { name: 'Honduras', value: 'hnd' },
  { name: 'Hungary', value: 'hun' },
  { name: 'Iceland', value: 'isl' },
  { name: 'India', value: 'ind' },
  { name: 'Indonesia', value: 'idn' },
  { name: 'Iran', value: 'irn' },
  { name: 'Iraq', value: 'irq' },
  { name: 'Ireland', value: 'irl' },
  { name: 'Israel', value: 'isr' },
  { name: 'Italy', value: 'ita' },
  { name: 'Jamaica', value: 'jam' },
  { name: 'Japan', value: 'jpn' },
  { name: 'Jordan', value: 'jor' },
  { name: 'Kazakhstan', value: 'kaz' },
  { name: 'Kenya', value: 'ken' },
  { name: 'Kiribati', value: 'kir' },
  { name: 'Kuwait', value: 'kwt' },
  { name: 'Kyrgyzstan', value: 'kgz' },
  { name: 'Laos', value: 'lao' },
  { name: 'Latvia', value: 'lva' },
  { name: 'Lebanon', value: 'lbn' },
  { name: 'Lesotho', value: 'lso' },
  { name: 'Liberia', value: 'lbr' },
  { name: 'Libya', value: 'lby' },
  { name: 'Liechtenstein', value: 'lie' },
  { name: 'Lithuania', value: 'ltu' },
  { name: 'Luxembourg', value: 'lux' },
  { name: 'Madagascar', value: 'mdg' },
  { name: 'Malawi', value: 'mwi' },
  { name: 'Malaysia', value: 'mys' },
  { name: 'Maldives', value: 'mdv' },
  { name: 'Mali', value: 'mli' },
  { name: 'Malta', value: 'mlt' },
  { name: 'Marshall Islands', value: 'mhl' },
  { name: 'Mauritania', value: 'mrt' },
  { name: 'Mauritius', value: 'mus' },
  { name: 'Mexico', value: 'mex' },
  { name: 'Micronesia', value: 'fsm' },
  { name: 'Moldova', value: 'mda' },
  { name: 'Monaco', value: 'mco' },
  { name: 'Mongolia', value: 'mng' },
  { name: 'Montenegro', value: 'mne' },
  { name: 'Morocco', value: 'mar' },
  { name: 'Mozambique', value: 'moz' },
  { name: 'Myanmar', value: 'mmr' },
  { name: 'Namibia', value: 'nam' },
  { name: 'Nauru', value: 'nru' },
  { name: 'Nepal', value: 'npl' },
  { name: 'Netherlands', value: 'nld' },
  { name: 'New Zealand', value: 'nzl' },
  { name: 'Nicaragua', value: 'nic' },
  { name: 'Niger', value: 'ner' },
  { name: 'Nigeria', value: 'nga' },
  { name: 'North Korea', value: 'prk' },
  { name: 'North Macedonia', value: 'mkd' },
  { name: 'Norway', value: 'nor' },
  { name: 'Oman', value: 'omn' },
  { name: 'Pakistan', value: 'pak' },
  { name: 'Palau', value: 'plw' },
  { name: 'Palestine', value: 'pse' },
  { name: 'Panama', value: 'pan' },
  { name: 'Papua New Guinea', value: 'png' },
  { name: 'Paraguay', value: 'pry' },
  { name: 'Peru', value: 'per' },
  { name: 'Philippines', value: 'phl' },
  { name: 'Poland', value: 'pol' },
  { name: 'Portugal', value: 'prt' },
  { name: 'Qatar', value: 'qat' },
  { name: 'Romania', value: 'rou' },
  { name: 'Russia', value: 'rus' },
  { name: 'Rwanda', value: 'rwa' },
  { name: 'Saint Kitts and Nevis', value: 'kna' },
  { name: 'Saint Lucia', value: 'lca' },
  { name: 'Saint Vincent and the Grenadines', value: 'vct' },
  { name: 'Samoa', value: 'wsm' },
  { name: 'San Marino', value: 'smr' },
  { name: 'Sao Tome and Principe', value: 'stp' },
  { name: 'Saudi Arabia', value: 'sau' },
  { name: 'Senegal', value: 'sen' },
  { name: 'Serbia', value: 'srb' },
  { name: 'Seychelles', value: 'syc' },
  { name: 'Sierra Leone', value: 'sle' },
  { name: 'Singapore', value: 'sgp' },
  { name: 'Slovakia', value: 'svk' },
  { name: 'Slovenia', value: 'svn' },
  { name: 'Solomon Islands', value: 'slb' },
  { name: 'Somalia', value: 'som' },
  { name: 'South Africa', value: 'zaf' },
  { name: 'South Korea', value: 'kor' },
  { name: 'South Sudan', value: 'ssd' },
  { name: 'Spain', value: 'esp' },
  { name: 'Sri Lanka', value: 'lka' },
  { name: 'Sudan', value: 'sdn' },
  { name: 'Suriname', value: 'sur' },
  { name: 'Sweden', value: 'swe' },
  { name: 'Switzerland', value: 'che' },
  { name: 'Syria', value: 'syr' },
  { name: 'Taiwan', value: 'twn' },
  { name: 'Tajikistan', value: 'tjk' },
  { name: 'Tanzania', value: 'tza' },
  { name: 'Thailand', value: 'tha' },
  { name: 'Timor-Leste', value: 'tls' },
  { name: 'Togo', value: 'tgo' },
  { name: 'Tonga', value: 'ton' },
  { name: 'Trinidad and Tobago', value: 'tto' },
  { name: 'Tunisia', value: 'tun' },
  { name: 'Turkey', value: 'tur' },
  { name: 'Turkmenistan', value: 'tkm' },
  { name: 'Tuvalu', value: 'tuv' },
  { name: 'Uganda', value: 'uga' },
  { name: 'Ukraine', value: 'ukr' },
  { name: 'United Arab Emirates', value: 'are' },
  { name: 'United Kingdom', value: 'gbr' },
  { name: 'United States', value: 'usa' },
  { name: 'Uruguay', value: 'ury' },
  { name: 'Uzbekistan', value: 'uzb' },
  { name: 'Vanuatu', value: 'vut' },
  { name: 'Vatican City', value: 'vat' },
  { name: 'Venezuela', value: 'ven' },
  { name: 'Vietnam', value: 'vnm' },
  { name: 'Yemen', value: 'yem' },
  { name: 'Zambia', value: 'zmb' },
  { name: 'Zimbabwe', value: 'zwe' },
];
